version: '3'

services:
  web:
    build: .
    container_name: web
    command: avvoka_app/bin/rails server -b0.0.0.0
    volumes:
      - .:/app #
    ports:
      - 3000:3000

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    links:
      - web

volumes:
  mysql-data:
    driver: local
